### ISSUE TITLE
Cleanup Dependencies (Nice to Have)

### ISSUE THREAD

**Issue by jd-carroll** [Famous/framework#27]
It would be nice to have the dependencies in package.json cleaned up a little and have the dev-dependencies separate from the runtime dependencies.  This way it's easier to get a better understanding of what all will be included.

**Comment by matthewtoast** [comment]
Agree that we should do an audit of this. Several of the dependencies that might seem like devDependencies are (currently) dependencies in our case, since our build tools are (currently) required for creating components. It may require a deeper refactor to get this cleaned up properly and make the runtime dependencies a lot more lightweight.
